name: Publish NuGet package

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: true
        type: boolean
        default: true
  schedule:
    - cron: '21 3 * * 1'

jobs:
  preflight:
    name: Preflight
    runs-on: windows-2022
    outputs:
      dry-run: ${{ steps.get-dry-run.outputs.dry-run }}
      package-version: ${{ steps.get-version.outputs.package-version }}

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Get dry run
        id: get-dry-run
        run: |
          $IsDryRun = '${{ github.event.inputs.dry-run }}' -Eq 'true' -Or '${{ github.event_name }}' -Eq 'schedule'

          if ($IsDryRun) {
            echo "dry-run=true" >> $Env:GITHUB_OUTPUT
          } else {
            echo "dry-run=false" >> $Env:GITHUB_OUTPUT
          }
        shell: pwsh

      - name: Get version
        id: get-version
        run: |
          $CsprojXml = [Xml](Get-Content .\ffi\dotnet\Devolutions.IronRdp\Devolutions.IronRdp.csproj)
          $ProjectVersion = $CsprojXml.Project.PropertyGroup.Version | Select-Object -First 1
          $PackageVersion = $ProjectVersion -Replace "^(\d+)\.(\d+)\.(\d+).(\d+)$", "`$1.`$2.`$3"
          echo "package-version=$PackageVersion" >> $Env:GITHUB_OUTPUT
        shell: pwsh

  build:
    name: Build Windows NuGet package
    needs: [preflight]
    runs-on: windows-2022

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Install dependencies for rustls
        run: |
          choco install ninja nasm
          Write-Output "PATH=$Env:PATH;$Env:ProgramFiles\NASM" >> $Env:GITHUB_ENV
        shell: pwsh

      - name: Build native library
        run: |
          $PackageVersion = '${{ needs.preflight.outputs.package-version }}'
          $CargoToml = Get-Content .\ffi\Cargo.toml
          $CargoToml = $CargoToml | ForEach-Object {
            if ($_.StartsWith("version =")) { "version = `"$PackageVersion`"" } else { $_ }
          }
          Set-Content -Path .\ffi\Cargo.toml -Value $CargoToml

          cargo build -p ffi --profile production-ffi
          New-Item -ItemType Directory -Force -Path .\dependencies\runtimes\win-x64\native | Out-Null
          Copy-Item .\target\production-ffi\ironrdp.dll .\dependencies\runtimes\win-x64\native\DevolutionsIronRdp.dll
        shell: pwsh

      - name: Build managed package
        run: dotnet build .\ffi\dotnet\Devolutions.IronRdp\Devolutions.IronRdp.csproj -c Release
        shell: pwsh

      - name: Upload managed components
        uses: actions/upload-artifact@v4
        with:
          name: ironrdp-nupkg
          path: ffi/dotnet/Devolutions.IronRdp/bin/Release/*.nupkg

  publish:
    name: Publish NuGet package
    environment: nuget-publish
    if: ${{ needs.preflight.outputs.dry-run == 'false' }}
    needs: [preflight, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: ironrdp-nupkg
          path: package

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_BOT_USERNAME }}

      - name: Publish to nuget.org
        run: |
          $Files = Get-ChildItem -Recurse package/*.nupkg

          foreach ($File in $Files) {
            $PushCmd = @(
              'dotnet',
              'nuget',
              'push',
              "$File",
              '--api-key',
              '${{ steps.nuget-login.outputs.NUGET_API_KEY }}',
              '--source',
              'https://api.nuget.org/v3/index.json',
              '--skip-duplicate'
            )

            Write-Host "Publishing $($File.Name)..."
            $PushCmd = $PushCmd -Join ' '
            Invoke-Expression $PushCmd
          }
        shell: pwsh
